{
    "openapi": "3.0.1",
    "info": {
        "title": "UIDAM-USER-MANAGEMENT",
        "description": "This provides uidam-user-management services",
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://api-gateway.ecsp.com/"
        }
    ],
    "paths": {
        "/v1/users/self/settings/{cloudProfileName}/map": {
            "get": {
                "tags": [
                    "end user"
                ],
                "summary": "Get my user cloud setting",
                "description": "Get my user cloud profile data <br /><br />\nAllowed scopes: SelfManage <br />\nETag behavior differs slightly from RFC specifications: <br />\n- No support for list, only 1 ETag at a time <br />\n- No support for '*' value. Either a specific value needs to be used or none at all\n<br>end user-getCloudProfileMap<p style='color:red;'>SCOPE: [SelfManage]</p>",
                "operationId": "getCloudProfileMap",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "SelfManage"
                        ]
                    }
                ]
            },
            "put": {
                "tags": [
                    "end user"
                ],
                "summary": "Create or update a new cloud profile for user",
                "description": "This API creates a new profile for user or overwrites existing profile if already exists <br /><br />\nAllowed scopes: SelfManage <br />\nETag behavior differs slightly from RFC specifications: <br />\n- No support for list, only 1 ETag at a time <br />\n- No support for '*' value. Either a specific value needs to be used or none at all\n<br>end user-updateCloudProfile<p style='color:red;'>SCOPE: [SelfManage]</p>",
                "operationId": "updateCloudProfile",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "SelfManage"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "end user"
                ],
                "summary": "Delete a cloud profile for user",
                "description": "Delete a specific profile for the user. <br /><br />\nAllowed scopes: SelfManage <br />\nETag behavior differs slightly from RFC specifications: <br />\n- No support for list, only 1 ETag at a time <br />\n- No support for '*' value. Either a specific value needs to be used or none at all\n<br>end user-deleteCloudProfile<p style='color:red;'>SCOPE: [SelfManage]</p>",
                "operationId": "deleteCloudProfile",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "SelfManage"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "end user"
                ],
                "summary": "Create or update a new cloud profile for user",
                "description": "This API creates a new profile for user or updates specific fields in existing profile\nif already exists. <br /><br />\nAllowed scopes: SelfManage <br />\nETag behavior differs slightly from RFC specifications: <br />\n- No support for list, only 1 ETag at a time <br />\n- No support for '*' value. Either a specific value needs to be used or none at all\n<br>end user-editCloudProfile<p style='color:red;'>SCOPE: [SelfManage]</p>",
                "operationId": "editCloudProfile",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "SelfManage"
                        ]
                    }
                ]
            }
        },
        "/v1/users/attributes": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "Get user attributes",
                "description": "Get user's entity attributes.<br>users-getUserAttributes<p style='color:red;'>SCOPE: [ViewUsers, ManageUsers]</p>",
                "operationId": "getUserAttributes",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ViewUsers",
                            "ManageUsers"
                        ]
                    }
                ]
            },
            "put": {
                "tags": [
                    "users"
                ],
                "summary": "Add/Modify additional attributes to user",
                "description": "Add/Modify additional attributes to user entity.<br>users-putUserAttributes<p style='color:red;'>SCOPE: [ManageUsers]</p>",
                "operationId": "putUserAttributes",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUsers"
                        ]
                    }
                ]
            }
        },
        "/v1/oauth2/client/{clientId}": {
            "get": {
                "tags": [
                    "client-registration-controller"
                ],
                "summary": "Get ClientDetails",
                "description": "Get registered client details<br>client-registration-controller-getClient<p style='color:red;'>SCOPE: [OAuth2ClientMgmt]</p>",
                "operationId": "getClient",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "OAuth2ClientMgmt"
                        ]
                    }
                ]
            },
            "put": {
                "tags": [
                    "client-registration-controller"
                ],
                "summary": "update client",
                "description": "update existing client<br>client-registration-controller-updateClient<p style='color:red;'>SCOPE: [OAuth2ClientMgmt]</p>",
                "operationId": "updateClient",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "OAuth2ClientMgmt"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "client-registration-controller"
                ],
                "summary": "delete client",
                "description": "delete existing client<br>client-registration-controller-deleteClient<p style='color:red;'>SCOPE: [OAuth2ClientMgmt]</p>",
                "operationId": "deleteClient",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "OAuth2ClientMgmt"
                        ]
                    }
                ]
            }
        },
        "/v1/users": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Add a new user",
                "description": "Creates a new user.<br>users-addUser<p style='color:red;'>SCOPE: [ManageUsers]</p>",
                "operationId": "addUser",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUsers"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "users"
                ],
                "summary": "Delete users that match defined criteria",
                "description": "Delete users that match defined criteria<br>users-deleteUsersByFilter<p style='color:red;'>SCOPE: [ManageUsers]</p>",
                "operationId": "deleteUsersByFilter",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUsers"
                        ]
                    }
                ]
            }
        },
        "/v1/users/self/settings": {
            "get": {
                "tags": [
                    "end user"
                ],
                "summary": "Get my user cloud profile (setting) names and etags",
                "description": "Get my user cloud profile names and etags <br /><br />\nAllowed scopes: SelfManage <br />\nETag behavior differs slightly from RFC specifications: <br />\n- No support for list, only 1 ETag at a time <br />\n- No support for '*' value. Either a specific value needs to be used or none at all\n<br>end user-getCloudProfiles<p style='color:red;'>SCOPE: [SelfManage]</p>",
                "operationId": "getCloudProfiles",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "SelfManage"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "cloud-profile-controller"
                ],
                "summary": "addCloudProfile api call",
                "description": " <br>cloud-profile-controller-addCloudProfile<p style='color:red;'> WARNING!! - Security Config Not Found </p>",
                "operationId": "addCloudProfile"
            }
        },
        "/v1/users/filter": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Retrieve users that match defined criteria",
                "description": "'Retrieves users that match items in the defined list of parameters and values.'  List of parameters can contain dynamic attributes only if they were defined as 'searchable'.<br>users-getUsers<p style='color:red;'>SCOPE: [ViewUsers, ManageUsers]</p>",
                "operationId": "getUsers",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ViewUsers",
                            "ManageUsers"
                        ]
                    }
                ]
            }
        },
        "/v1/users/external": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Add a new external user",
                "description": "Creates a new external user.<br>users-addExternalUser<p style='color:red;'>SCOPE: [ManageUsers]</p>",
                "operationId": "addExternalUser",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUsers"
                        ]
                    }
                ]
            }
        },
        "/v1/scopes": {
            "post": {
                "tags": [
                    "scopes-controller"
                ],
                "summary": "Create New Scope",
                "description": "Create a new scope<br>scopes-controller-createScope<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "createScope",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            }
        },
        "/v1/scopes/filter": {
            "post": {
                "tags": [
                    "scopes-controller"
                ],
                "summary": "Filter Scope",
                "description": "Filter scope details<br>scopes-controller-filterScopes<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "filterScopes",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            }
        },
        "/v1/roles": {
            "post": {
                "tags": [
                    "roles-controller"
                ],
                "summary": "Create Role",
                "description": "Create a new role<br>roles-controller-createRole<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "createRole",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            }
        },
        "/v1/roles/rolesById": {
            "post": {
                "tags": [
                    "roles-controller"
                ],
                "summary": "Get Role By Id",
                "description": "Get role information by role id<br>roles-controller-getRoleById<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "getRoleById",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            }
        },
        "/v1/roles/filter": {
            "post": {
                "tags": [
                    "roles-controller"
                ],
                "summary": "Filter Role",
                "description": "Get multiple roles information by role names<br>roles-controller-filterRoles<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "filterRoles",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            }
        },
        "/v1/oauth2/client": {
            "post": {
                "tags": [
                    "client-registration-controller"
                ],
                "summary": "Create client",
                "description": "register a new client<br>client-registration-controller-createClient<p style='color:red;'>SCOPE: [OAuth2ClientMgmt]</p>",
                "operationId": "createClient",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "OAuth2ClientMgmt"
                        ]
                    }
                ]
            }
        },
        "/v1/accounts": {
            "post": {
                "tags": [
                    "account"
                ],
                "summary": "Create a new account",
                "description": "Creates a new Account.<br>account-createAccount<p style='color:red;'>SCOPE: [ManageAccounts]</p>",
                "operationId": "createAccount",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageAccounts"
                        ]
                    }
                ]
            }
        },
        "/v1/accounts/{account_id}": {
            "get": {
                "tags": [
                    "account"
                ],
                "summary": "Get account details",
                "description": "Gets the account identified by its ID<br>account-getAccount<p style='color:red;'>SCOPE: [ViewAccounts, ManageAccounts]</p>",
                "operationId": "getAccount",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ViewAccounts",
                            "ManageAccounts"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "account"
                ],
                "summary": "Update an existing account",
                "description": "Update an existing account<br>account-updateAccount<p style='color:red;'>SCOPE: [ManageAccounts]</p>",
                "operationId": "updateAccount",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageAccounts"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "account"
                ],
                "summary": "Delete an existing account",
                "description": "Account must not be default and no users associated<br>account-deleteAccount<p style='color:red;'>SCOPE: [ManageAccounts]</p>",
                "operationId": "deleteAccount",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageAccounts"
                        ]
                    }
                ]
            }
        },
        "/v1/accounts/filter": {
            "post": {
                "tags": [
                    "account"
                ],
                "summary": "Retrieve accounts that match the defined criteria",
                "description": "Retrieves Accounts that match items in the defined list of parameters and values.<br>account-filterAccounts<p style='color:red;'>SCOPE: [ViewAccounts, ManageAccounts]</p>",
                "operationId": "filterAccounts",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ViewAccounts",
                            "ManageAccounts"
                        ]
                    }
                ]
            }
        },
        "/v1/users/{id}": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "Get a user",
                "description": "Gets a single user identified by its ID<br>users-getUser<p style='color:red;'>SCOPE: [ViewUsers, ManageUsers]</p>",
                "operationId": "getUser",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ViewUsers",
                            "ManageUsers"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "users"
                ],
                "summary": "Delete a user",
                "description": "Deletes a single user identified by its ID<br>users-deleteUser<p style='color:red;'>SCOPE: [ManageUsers]</p>",
                "operationId": "deleteUser",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUsers"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "users"
                ],
                "summary": "Update a user",
                "description": "Updates a single user identified by its ID<br>users-editUser<p style='color:red;'>SCOPE: [ManageUsers]</p>",
                "operationId": "editUser",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUsers"
                        ]
                    }
                ]
            }
        },
        "/v1/users/status": {
            "patch": {
                "tags": [
                    "users"
                ],
                "summary": "Change user status",
                "description": "Change status for users.<br>users-changeUserStatus<p style='color:red;'>SCOPE: [ManageUsers]</p>",
                "operationId": "changeUserStatus",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUsers"
                        ]
                    }
                ]
            }
        },
        "/v1/users/self": {
            "get": {
                "tags": [
                    "end user"
                ],
                "summary": "Get my user data",
                "description": "Get my user data<br>end user-getSelfUser<p style='color:red;'>SCOPE: [SelfManage]</p>",
                "operationId": "getSelfUser",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "SelfManage"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "end user"
                ],
                "summary": "Delete my own user",
                "description": "Delete my own user<br>end user-deleteSelfUser<p style='color:red;'>SCOPE: [SelfManage]</p>",
                "operationId": "deleteSelfUser",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "SelfManage"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "end user"
                ],
                "summary": "Update logged in user.",
                "description": "Update logged in user.<br>end user-editSelfUser<p style='color:red;'>SCOPE: [SelfManage]</p>",
                "operationId": "editSelfUser",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "SelfManage"
                        ]
                    }
                ]
            }
        },
        "/v1/scopes/{name}": {
            "get": {
                "tags": [
                    "scopes-controller"
                ],
                "summary": "Get Scope",
                "description": "Get scope details<br>scopes-controller-getScope<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "getScope",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "scopes-controller"
                ],
                "summary": "Delete Scope",
                "description": "Delete scope<br>scopes-controller-deleteScope<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "deleteScope",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "scopes-controller"
                ],
                "summary": "Update Scope",
                "description": "Update scope details<br>scopes-controller-updateScope<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "updateScope",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            }
        },
        "/v1/roles/{name}": {
            "get": {
                "tags": [
                    "roles-controller"
                ],
                "summary": "Get Role By Name",
                "description": "Get role information by role name<br>roles-controller-getRole<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "getRole",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "roles-controller"
                ],
                "summary": "Delete Role",
                "description": "Deletes a single role using its unique name.<br>roles-controller-deleteRole<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "deleteRole",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "roles-controller"
                ],
                "summary": "Update Role",
                "description": "Update existing role details<br>roles-controller-updateRole<p style='color:red;'>SCOPE: [ManageUserRolesAndPermissions]</p>",
                "operationId": "updateRole",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUserRolesAndPermissions"
                        ]
                    }
                ]
            }
        },
        "/v1/users/self/settings/{cloudProfileName}": {
            "get": {
                "tags": [
                    "end user"
                ],
                "summary": "Get my user cloud profile (setting) etag",
                "description": "Get my user cloud profile etag in response body <br /><br />\nAllowed scopes: SelfManage <br />\nETag behavior differs slightly from RFC specifications: <br />\n- No support for list, only 1 ETag at a time <br />\n- No support for '*' value. Either a specific value needs to be used or none at all\n<br>end user-getCloudProfile<p style='color:red;'>SCOPE: [SelfManage]</p>",
                "operationId": "getCloudProfile",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "SelfManage"
                        ]
                    }
                ]
            }
        },
        "/v1/users/external/{id}": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "Get external user",
                "description": "Gets a single external user identified by its ID.<br>users-getExternalUser<p style='color:red;'>SCOPE: [ViewUsers, ManageUsers]</p>",
                "operationId": "getExternalUser",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ViewUsers",
                            "ManageUsers"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "users"
                ],
                "summary": "Delete an external user",
                "description": "Deletes a single external user identified by its ID<br>users-deleteExternalUser<p style='color:red;'>SCOPE: [ManageUsers]</p>",
                "operationId": "deleteExternalUser",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ManageUsers"
                        ]
                    }
                ]
            }
        },
        "/v1/emailVerification/{userId}/isEmailVerified": {
            "get": {
                "tags": [
                    "email"
                ],
                "summary": "Get if user email was verified by user id",
                "description": "Get if user email was verified by user id.<br>email-getIsEmailVerified<p style='color:red;'>SCOPE: [ViewUsers, ManageUsers]</p>",
                "operationId": "getIsEmailVerified",
                "security": [
                    {
                        "JwtAuthValidator": [
                            "ViewUsers",
                            "ManageUsers"
                        ]
                    }
                ]
            }
        },
        "/v1/emailVerification/{token}": {
            "get": {
                "tags": [
                    "email"
                ],
                "summary": "Verify email address via UUID",
                "description": "API requires only a valid link (i.e. UUID) to validate an email.<br>email-verifyEmail<p style='color:red;'> WARNING!! - Security Config Not Found </p>",
                "operationId": "verifyEmail"
            }
        }
    },
    "components": {
    }
}